/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef POL2PDF
#define POL2PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class Pol2Pdf : public RooAbsPdf {
public:
  Pol2Pdf() {} ;
  Pol2Pdf(const char *name, const char *title,
	    RooAbsReal& _x,
	    RooAbsReal& _A,
	    RooAbsReal& _B,
            RooAbsReal& _C);
  Pol2Pdf(const Pol2Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Pol2Pdf(*this,newname); }
  inline virtual ~Pol2Pdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;

  Double_t evaluate() const ;

private:

  ClassDef(Pol2Pdf,1) // Your description goes here...
};

#endif
