/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef POL3PDF
#define POL3PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class Pol3Pdf : public RooAbsPdf {
public:
  Pol3Pdf() {} ;
  Pol3Pdf(const char *name, const char *title,
	    RooAbsReal& _x,
	    RooAbsReal& _A,
	    RooAbsReal& _B,
            RooAbsReal& _C,
            RooAbsReal& _D);
  Pol3Pdf(const Pol3Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Pol3Pdf(*this,newname); }
  inline virtual ~Pol3Pdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;
  RooRealProxy D ;

  Double_t evaluate() const ;

private:

  ClassDef(Pol3Pdf,1) // Your description goes here...
};

#endif
